services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: search_engine_api
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./var/cache:/var/www/html/var/cache
      - ./var/log:/var/www/html/var/log
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - search_engine_network
    depends_on:
      mysql:
        condition: service_healthy # MySQL çalısana bekle
    environment:
      - APP_ENV=dev
      - DATABASE_URL=mysql://search_user:search_password@mysql:3306/search_engine_db?serverVersion=8.0.32&charset=utf8mb4
    user: "1000:1000"

  nginx:
    image: nginx:alpine
    container_name: search_engine_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - search_engine_network
    depends_on:
      - app # Nginx, uygulamanın çalışır duruma gelmesini bekler

  mysql:
    image: mysql:8.0
    container_name: search_engine_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: search_engine_db
      MYSQL_USER: search_user
      MYSQL_PASSWORD: search_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - search_engine_network
    healthcheck: # MySQL için check eklendi
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u$$MYSQL_USER", "-p$$MYSQL_PASSWORD"]
      timeout: 20s
      retries: 10
      start_period: 20s # MySQL'in başlaması için ilk bekleme süresi

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: search_engine_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_USER: search_user
      PMA_PASSWORD: search_password
    ports:
      - "8081:80"
    networks:
      - search_engine_network
    depends_on:
      - mysql # PhpMyAdmin, MySQL'in başlamasını bekler

volumes:
  mysql_data:

networks:
  search_engine_network:
    driver: bridge